#!/bin/bash
###################
#### VARIABLES ####
###################

DBGLOG=/volume1/chia_data/mainnet/log/debug.log*
CHIACMD="docker exec chia venv/bin/chia"

#### PROOF RESPONSE THRESHOLDS (should never exceed 30 seconds) ####
PRSP_WARN="25"
PRSP_CRIT="30"

#### SIGNAGE POINT THRESHOLDS (should be 64 in 10 minutes) ####
SGNPNT_WARN="63"
SGNPNT_CRIT="62"

#### PLOT COUNT THRESHOLDS ####
PLTCNT_WARN="1700"
PLTCNT_CRIT="1000"
FRMSUMM=$(${CHIACMD} farm summary)

#### FULL_NODE CONNECTION THRESHOLDS ####
FNC_WARN="2"
FNC_CRIT="0"

farm_summary(){
STATUS=$(echo "${FRMSUMM}" | awk -F: '/Farming status/ {print $2}' | sed 's/^ *//g')
if [ "${STATUS}" == "Farming" ];then

                echo "0 \"CHIA status\" - ${STATUS}"

        else

                echo "2 \"CHIA status\" - ${STATUS}"

fi
}

chia_balance(){
BALANCE=$(echo "${FRMSUMM}" | awk -F: '/Total chia farmed/ {print $2}' | sed 's/^ *//g')

if [ -z $(echo ${BALANCE} | grep -E "[0-9].*") ];then

        echo "2 \"CHIA balance\" balance=${BALANCE} ${BALANCE}"

else

        echo "0 \"CHIA balance\" balance=${BALANCE} ${BALANCE}"

fi
}

plot_count(){
PLTCNT=$(echo "${FRMSUMM}" | awk -F: '/Plot count/ {print $2}' | sed 's/^ *//g')

if [ -z $(echo ${PLTCNT} | grep -E "[0-9].*") ];then

        echo "P \"CHIA plots\" plots=${PLTCNT};${PLTCNT_WARN}:;${PLTCNT_CRIT}:"

else

        echo "P \"CHIA plots\" plots=${PLTCNT};${PLTCNT_WARN}:;${PLTCNT_CRIT}:"

fi
}

check_version(){
LATEST=$(curl -s https://github.com/Chia-Network/chia-blockchain/tags | egrep "a href.*releases/tag/" | egrep -o "[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}" | head -1)
ACTIVE=$(${CHIACMD} version | egrep -o "[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}" | sed '/\ /d')
LATEST_NUMERIC=$(echo ${LATEST} | sed 's/\.//g')
ACTIVE_NUMERIC=$(echo ${ACTIVE} | sed 's/\.//g')

if [ ! -z "${LATEST_NUMERIC}" -a "${ACTIVE_NUMERIC}" ];then

        if [ ${LATEST_NUMERIC} -gt ${ACTIVE_NUMERIC} ]; then

                echo "2 \"CHIA latest version is\" - ${LATEST} running: ${ACTIVE}"

        else

                echo "0 \"CHIA latest version is\" - ${LATEST} running: ${ACTIVE}"
        fi
fi
}

proof_eligible_per_minute(){
LMIN=$(date -d '1 minute ago' '+%Y-%m-%dT%H:%M')
PEPM=$(grep ${LMIN} ${DBGLOG} | egrep -o "INFO.*[0-9].*eligible for farming" | wc -l)

echo "P \"CHIA proofs eligible / min \" pepm=${PEPM} ${PEPM} at ${LMIN##*T}"
}

proof_response_time(){
LMIN=$(date -d '1 minute ago' '+%Y-%m-%dT%H:%M')
PRSP=$(grep ${LMIN} ${DBGLOG} | awk '/INFO.*plots were eligible for farming.*Found.*proofs.*Time: [0-9]{1,5}.[0-9]{1,5} s/ {print $16}' | sort | tail -1)

echo "P \"CHIA proof response\" response_time=${PRSP};${PRSP_WARN};${PRSP_CRIT} worst last minute in seconds"
}

signage_points(){
LSTSUBSLCT=$(awk '/full_node.*INFO.*Finished sub slot.*64\/64/ {print $1}' ${DBGLOG} | egrep -o '.*-.*-.*T[0-9]{1,2}:[0-9]{1,2}' | sort | tail -1)
LMIN=$(date -d "${LSTSUBSLCT} 10 minutes ago" '+%Y-%m-%dT%H:%M')
SGNPNT=$(sed -n /${LMIN}/,/${LSTSUBSLCT}/p ${DBGLOG} | egrep -o '[0-9]{1,2}\/64' | sed '/\ /d' | sort -u | wc -l)


echo "P \"CHIA signage points last 10 minutes\" signage_points=${SGNPNT};${SGNPNT_WARN}:;${SGNPNT_CRIT}:"

}

time_to_win(){
TTW=$(echo "${FRMSUMM}" | awk -F: '/Expected time to win:/ {print $2}')

echo "P \"CHIA expected time to win\" - ${TTW}"
}

blockchain_status(){
BCS=$(${CHIACMD} show -s | awk -F: '/Current Blockchain Status/ {print $2}' | xargs)

if [ "${BCS}" == "Full Node Synced" ]; then

        echo "0 \"CHIA chain status\" - ${BCS}"

else

    echo "2 \"CHIA chain status\" - ${BCS}"

fi
}

full_node_connections(){

FNC=$(${CHIACMD} show -c | grep FULL_NODE | wc -l)

echo "P \"CHIA full node Connections\" connections=${FNC};${FNC_WARN}:;${FNC_CRIT}:"
}

farm_summary
blockchain_status
chia_balance
plot_count
time_to_win
check_version
proof_eligible_per_minute
proof_response_time
signage_points
full_node_connections
